import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Link, Route, Switch, useLocation } from 'wouter';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronDown, IndianRupee, PiggyBank, ShieldCheck } from 'lucide-react';
import { AdminApp } from './admin/AdminApp';
import { CardStack, Parallax, ScrollProgress } from './components/scroll-effects';
import { ButtonLink, PageIntro, Shell } from './components/shell';
import { fmt, useLoanTypes, useSiteConfig } from './lib/data';
import { AuthPage } from './pages/Auth';
import { Eligibility } from './pages/Eligibility';
import { Apply } from './pages/Apply';
import { Contact } from './pages/Contact';
import { ApplicationDetail, Applications, Profile } from './pages/Account';

function Home() {
 const {loanTypes}=useLoanTypes();
 const site=useSiteConfig();
 const [faq,setFaq]=useState<number|null>(0);
 const questions=[['Who actually provides my loan?','Chakrapay is a loan service provider (LSP), not the lender. If you apply, a partner NBFC checks your application. The partner NBFC takes the final decision on sanction and disbursal.'],['Are these rates guaranteed?','No. All amounts, interest rates, EMIs and eligibility results on this site are indicative only. The lender tells you the real terms after checking your application.'],['Do I pay a fee to apply?','We do not charge any advance or processing fee. Never pay anyone who promises you a loan approval.']];
 return <Shell>
  <section className="overflow-hidden bg-[#ebf1f8]"><div className="page-wrap grid min-h-[600px] items-center gap-8 py-12 md:grid-cols-[1fr_.88fr] md:py-16">
    <div className="relative z-10 reveal"><div className="eyebrow flex items-center gap-2"><span className="h-px w-7 bg-[#34a7ee]"/>Simple loans, honest answers</div><h1 className="serif mt-6 max-w-[720px] text-[3rem] leading-[1.02] tracking-[-.04em] text-[#10244d] sm:text-[3.5rem] md:text-[4.5rem]">Find the right loan,<br/><em className="font-normal text-[#2b93d4]">without the guesswork.</em></h1><p className="mt-6 max-w-[500px] text-[1.06rem] leading-7 text-[#4a608b]">Check your EMI and see if you may be eligible, in just a few minutes. Clear words, no hidden surprises, and no pressure to apply.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/eligibility" testid="hero-check-eligibility">Check my eligibility <ArrowDownRight size={16}/></ButtonLink><ButtonLink href="/loans" secondary testid="hero-explore-loans">See loan options</ButtonLink></div><div className="mt-8 flex items-center gap-3 text-xs text-[#556c99]"><ShieldCheck size={17}/><span>Free to apply · We never ask for any advance or processing fee</span></div></div>
    <Parallax><div className="relative reveal delay-2"><span className="absolute -right-5 -top-5 -z-10 h-40 w-40 rounded-full bg-[#34a7ee]/25"/><span className="absolute -bottom-6 -left-6 -z-10 h-32 w-32 rounded-full bg-[#0040b8]/15"/><div className="overflow-hidden rounded-[30px] shadow-[0_30px_60px_-30px_#0b2160aa]"><img src="/images/hero-family.jpg" alt="An Indian mother and her daughter laughing together on a sofa at home" width="1000" height="630" fetchPriority="high" className="h-[300px] w-full scale-110 object-cover md:h-[430px]" data-depth="0.05"/></div><div className="absolute left-4 top-4 rounded-2xl bg-white/90 px-4 py-3 shadow-lg backdrop-blur md:left-6 md:top-6"><span className="serif text-2xl text-[#10244d] md:text-3xl">Know first,<br/>apply later.</span><p className="mt-1 text-[.62rem] font-bold tracking-[.12em] text-[#4f648d]">AT YOUR OWN PACE</p></div><div className="absolute -bottom-5 right-4 rounded-2xl bg-[#0b2160] px-4 py-3 text-xs text-[#dbe7ff] shadow-xl md:right-8"><span className="font-bold text-white">Check your EMI first.</span><br/>Apply only when you feel ready.</div></div></Parallax>
  </div></section>
  <section className="page-wrap py-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">A good place to begin</p><h2 className="serif mt-3 text-4xl text-[#10244d] md:text-[3.5rem]">What are you working towards?</h2></div><Link href="/loans" className="inline-flex items-center gap-2 pb-2 text-sm font-bold text-[#213f7a]">See every option <ArrowRight size={16}/></Link></div>
    <div className="mt-9"><CardStack>{loanTypes.map(({id,name,intro,icon:Icon,tag,rate,amount,term},i)=><Link href={`/loans#${id}`} key={id} className="group card grid gap-6 overflow-hidden p-7 md:grid-cols-[1.2fr_1fr] md:p-9" data-testid={`card-loan-${id}`}><div><div className="flex items-center gap-3"><span className={`flex h-12 w-12 items-center justify-center rounded-full ${i%2?'bg-[#e1eaf5] text-[#2788c4]':'bg-[#e4eaf6] text-[#213f7a]'}`}><Icon size={22}/></span><span className="eyebrow">0{i+1} · {tag}</span></div><h3 className="serif mt-6 text-3xl text-[#10244d] md:text-4xl">{name}</h3><p className="mt-3 max-w-sm text-[#596e99]">{intro}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#213f7a]">Explore {name.toLowerCase()} <ArrowUpRight size={16} className="transition-transform group-hover:-translate-y-1 group-hover:translate-x-1"/></span></div><dl className="grid content-center gap-4 rounded-2xl bg-[#e4ecf6] p-5 text-sm">{[['Amount',amount],['Indicative rate',rate],['Tenure',term]].map(([k,v])=><div key={k} className="flex justify-between gap-4 border-b border-[#bfd3ee] pb-3 last:border-0 last:pb-0"><dt className="text-[#6277a2]">{k}</dt><dd className="text-right font-bold text-[#1b2f58]">{v}</dd></div>)}</dl></Link>)}</CardStack></div>
  </section>
  <section className="bg-[#10244d] py-16 text-[#ebf1f8]"><div className="page-wrap grid items-center gap-10 md:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow !text-[#85bfe3]">Know before you decide</p><h2 className="serif mt-3 text-4xl leading-tight md:text-5xl">Know your EMI<br/>before you apply.</h2><p className="mt-5 max-w-lg leading-7 text-[#b4c1dc]">Check your EMI in a minute, or see if your income may match a lender's basic rules. It takes only a few minutes and nothing is saved in this demo.</p><div className="mt-7 flex flex-wrap gap-3"><ButtonLink href="/calculator">Calculate my EMI</ButtonLink><ButtonLink href="/eligibility" secondary>Check eligibility</ButtonLink></div></div><div className="rounded-[22px] border border-white/15 bg-white/[.06] p-7"><div className="flex items-center justify-between"><span className="eyebrow !text-[#85bfe3]">Example EMI</span><PiggyBank className="text-[#7dc6f4]"/></div><p className="serif mt-8 text-5xl">₹18,742<span className="ml-2 text-base text-[#b4c1dc]">/ month</span></p><div className="mt-6 grid grid-cols-2 gap-4 border-t border-white/15 pt-5 text-sm"><div><p className="text-[#9eafd1]">Loan amount</p><p className="mt-1 font-bold">₹10,00,000</p></div><div><p className="text-[#9eafd1]">Example rate</p><p className="mt-1 font-bold">12.5% p.a.</p></div></div><p className="mt-5 text-[.7rem] leading-5 text-[#a8b6d3]">This is an example. Your real rate and terms are decided by the partner lender.</p></div></div></section>
  <section className="page-wrap grid gap-10 py-20 md:grid-cols-[.8fr_1.2fr]"><div className="md:sticky md:top-28 md:h-fit"><p className="eyebrow">How it works</p><h2 className="serif mt-3 text-4xl leading-tight text-[#10244d] md:text-[3.2rem]">From first question<br/>to final answer.</h2><p className="mt-5 max-w-sm leading-7 text-[#4e638d]">Six easy steps. You can stop at any step. The partner lender, not us, takes the final decision.</p><img src="/images/how-it-works.jpg" alt="A smiling Indian family posing together" width="900" height="600" loading="lazy" className="mt-8 hidden w-full max-w-md rounded-3xl object-cover shadow-[0_24px_50px_-28px_#0b2160aa] md:block"/></div><ScrollProgress><div className="space-y-10">{[['Explore','Read about loan types, indicative rates and how long you can take to repay.'],['Estimate','Use the EMI calculator and check your eligibility.'],['Apply','Fill a short form with your basic details. No login needed to start.'],['Upload','Create an account to upload your KYC and income documents.'],['Track','See where your application stands, step by step.'],['Get an answer','The partner NBFC checks your application and decides. We keep you updated.']].map(([t,d],i)=><div key={t} data-step className="relative flex gap-5"><span className="step-dot z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-sm font-bold">{i+1}</span><div className="pt-1.5"><h3 className="text-lg font-bold text-[#1b2f58]">{t}</h3><p className="mt-1 max-w-md text-sm leading-6 text-[#596f9a]">{d}</p></div></div>)}</div></ScrollProgress></section>
  <section className="page-wrap grid gap-12 py-20 md:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Our promise to you</p><h2 className="serif mt-3 text-4xl leading-tight text-[#10244d] md:text-[3.4rem]">Simple words,<br/><em className="font-normal text-[#3198d8]">honest answers.</em></h2><p className="mt-5 max-w-md leading-7 text-[#4e638d]">We explain everything in easy language, so you can choose what is right for you and your family.</p><ButtonLink href="/about" secondary>How we work</ButtonLink><img src="/images/promise-family.jpg" alt="An Indian father lifting his laughing young child" width="800" height="1200" loading="lazy" className="mt-8 hidden h-72 w-full max-w-md rounded-3xl object-cover object-top shadow-[0_24px_50px_-28px_#0b2160aa] md:block"/></div><div className="grid gap-5 sm:grid-cols-2">{[['01','No pressure','Look around first. Applying is always your choice.'],['02','Plain language','We explain what every number means, in simple words.'],['03','Honest estimates','Every estimate is clearly marked as indicative. We never make false promises.'],['04','You stay in control','We never ask you for any advance or processing fee.']].map(([n,t,d])=><div key={n} className="border-t border-[#c8d2e7] pt-4"><span className="serif text-2xl text-[#3a9edc]">{n}</span><h3 className="mt-4 font-bold text-[#172c56]">{t}</h3><p className="mt-2 text-sm leading-6 text-[#536994]">{d}</p></div>)}</div></section>
  <section className="bg-[#e4eaf6] py-16"><div className="page-wrap grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Common questions, simple answers</p><h2 className="serif mt-3 text-4xl text-[#10244d]">Before you start.</h2><Link href="/contact" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#213f7a]">Still have a doubt? Talk to us <ArrowRight size={16}/></Link></div><div>{questions.map(([q,a],i)=><div className="faq-row" key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} data-testid={`faq-toggle-${i}`}><span>{q}</span><ChevronDown className={`transition-transform ${faq===i?'rotate-180':''}`} size={19}/></button>{faq===i&&<p className="max-w-2xl pb-5 text-sm leading-6 text-[#4e638d]" data-testid={`faq-answer-${i}`}>{a}</p>}</div>)}</div></div></section>
  <section className="page-wrap py-20"><div className="flex flex-col items-start justify-between gap-7 rounded-[26px] bg-[#cfe1f8] p-8 md:flex-row md:items-center md:p-12"><div><p className="eyebrow">No hurry</p><h2 className="serif mt-2 text-4xl text-[#10244d]">Take one small step today.</h2><p className="mt-3 max-w-xl text-[#52668f]">Start by checking your EMI. You do not need an account or an application.</p></div><ButtonLink href="/calculator">Try the EMI calculator</ButtonLink></div></section>
 </Shell>;
}

function Loans() {
 const {loanTypes}=useLoanTypes();
 const site=useSiteConfig();
 return <Shell><PageIntro eyebrow="Loan options" title={<>Choose a loan that<br/>fits your life and your budget.</>} desc="See the main types of loans and what you may need for each. Rates and terms are indicative. The final terms come from the partner NBFC."/>
  <div className="page-wrap py-14"><div className="grid gap-5 md:grid-cols-2">{loanTypes.map(({id,name,amount,rate,term,intro,icon:Icon,tag,eligibility,documents})=><article id={id} key={id} className="card scroll-mt-32 p-6 md:p-8" data-testid={`loan-detail-${id}`}><div className="flex items-start justify-between"><div><p className="eyebrow">{tag}</p><h2 className="mt-2 text-2xl font-bold text-[#10244d]">{name}</h2></div><span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#e4eaf6] text-[#254584]"><Icon/></span></div><p className="mt-3 text-sm leading-6 text-[#536893]">{intro}</p><div className="mt-6 grid grid-cols-3 gap-3 border-y border-[#c9daf1] py-4 text-xs"><div><span className="block text-[#6a7ea7]">Loan amount</span><b className="mt-1 block text-[#253c69]">{amount}</b></div><div><span className="block text-[#6a7ea7]">Interest rate (indicative)</span><b className="mt-1 block text-[#253c69]">{rate}</b></div><div><span className="block text-[#6a7ea7]">Repayment time</span><b className="mt-1 block text-[#253c69]">{term}</b></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-[#eaeef8] p-4"><p className="text-[.68rem] font-bold uppercase tracking-[.12em] text-[#4e6592]">Who can apply</p><p className="mt-2 text-xs leading-5 text-[#4f648d]">{eligibility}</p></div><div className="rounded-xl bg-[#e4ecf6] p-4"><p className="text-[.68rem] font-bold uppercase tracking-[.12em] text-[#2d77a5]">Documents you may need</p><p className="mt-2 text-xs leading-5 text-[#3f7393]">{documents}</p></div></div><p className="mt-4 text-xs leading-5 text-[#596e99]">{site.ratesDisclaimer}</p><div className="mt-4 rounded-lg border border-[#c9daf1] px-4 py-3 text-xs leading-5 text-[#4b608b]"><b>Fees:</b> {site.noFeeLine} If the partner NBFC has any charges, it must tell you clearly.</div><div className="mt-5 flex flex-wrap gap-3"><Link href={`/calculator?type=${id}`} className="btn btn-outline" data-testid={`calculate-${id}`}>Calculate EMI <ArrowRight size={15}/></Link><Link href={`/apply?type=${id}`} className="btn btn-primary" data-testid={`apply-${id}`}>Apply now <ArrowRight size={15}/></Link></div></article>)}</div><div className="mt-10 rounded-2xl bg-[#e4eaf6] p-6 text-sm leading-6 text-[#3e5582]"><b className="text-[#1b2f58]">Who provides the loan?</b> {site.lspStatement} Lender: {site.nbfc.url?<a href={site.nbfc.url} target="_blank" rel="noopener noreferrer" className="font-semibold underline">{site.nbfc.name}</a>:site.nbfc.name}. {site.noFeeLine}</div></div></Shell>;
}

function Calculator() {
 const params=new URLSearchParams(window.location.search);
 const {loanTypes}=useLoanTypes();
 const [sel,setSel]=useState(params.get('type')||'');
 const lt=loanTypes.find(l=>l.id===sel);
 const lo=lt?lt.min:50000,hi=lt?lt.max:5000000,maxYears=lt?Math.max(1,Math.ceil(lt.maxMonths/12)):30;
 const step=hi-lo>=10000000?500000:hi-lo>=1000000?25000:5000;
 const [amount,setAmount]=useState(Number(params.get('amount'))||1000000),[rate,setRate]=useState(12.5),[years,setYears]=useState(5);
 const pick=(id:string)=>{setSel(id);const t=loanTypes.find(l=>l.id===id);if(t){setRate(t.annualRate);setAmount(Math.min(t.max,Math.max(t.min,Math.round(Math.min(t.max,Math.max(t.min,1000000))/step)*step)));setYears(Math.max(1,Math.min(Math.ceil(t.maxMonths/12),5)))}};
 useEffect(()=>{if(sel&&lt)pick(sel)},[loanTypes.length]); // eslint-disable-line react-hooks/exhaustive-deps
 const monthly=rate/1200,months=years*12;
 const emi=monthly===0?amount/months:amount*monthly*Math.pow(1+monthly,months)/(Math.pow(1+monthly,months)-1);
 const interest=emi*months-amount;
 const currency=(v:number)=>`₹${fmt(v)}`;
 return <Shell><PageIntro eyebrow="Know your EMI" title="See your monthly EMI in seconds." desc="Move the sliders to see your monthly EMI. Pick a loan type to start with its indicative rate. No login needed, and nothing is saved."/>
  <div className="page-wrap grid gap-7 py-12 md:grid-cols-[1.1fr_.9fr] md:py-16"><section className="card p-6 md:p-9"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e4eaf6] text-[#234486]"><IndianRupee size={20}/></span><div><p className="eyebrow">EMI calculator</p><h2 className="font-bold text-[#182d57]">Set your amount</h2></div></div>
   <div className="mt-8 space-y-8"><label className="block"><span className="field-label">Loan type (optional)</span><select className="field" value={sel} onChange={e=>pick(e.target.value)} data-testid="select-calculator-loan-type"><option value="">Any loan</option>{loanTypes.map(l=><option key={l.id} value={l.id}>{l.name} · {l.rate}</option>)}</select></label><Slider label="Loan amount" value={Math.min(hi,Math.max(lo,amount))} min={lo} max={hi} step={step} display={currency(amount)} onChange={setAmount} testid="slider-loan-amount"/><Slider label="Interest rate (per year)" value={rate} min={6} max={30} step={0.25} display={`${rate.toFixed(2)}%`} onChange={setRate} testid="slider-interest-rate"/><Slider label="Repayment period" value={Math.min(years,maxYears)} min={1} max={maxYears} step={1} display={`${years} ${years===1?'year':'years'}`} onChange={setYears} testid="slider-tenure"/></div>
   <p className="mt-8 border-t border-[#d1dff1] pt-5 text-xs leading-5 text-[#79887e]">This uses the standard reducing-balance EMI formula. It does not include taxes, fees or any terms set by the lender. The result is an estimate only.</p></section>
   <aside className="flex flex-col justify-between rounded-[22px] bg-[#10244d] p-7 text-[#ebf1f8] md:p-9"><div><p className="eyebrow !text-[#78b4da]">Your monthly EMI</p><div className="serif mt-4 text-5xl md:text-6xl" data-testid="text-emi-result">{currency(emi)}<span className="ml-2 font-sans text-sm text-[#b4c1dc]">/ month</span></div><div className="mt-8 space-y-4 border-t border-white/15 pt-5 text-sm"><div className="flex justify-between"><span className="text-[#b4c1dc]">Principal</span><b>{currency(amount)}</b></div><div className="flex justify-between"><span className="text-[#b4c1dc]">Total interest</span><b>{currency(interest)}</b></div><div className="flex justify-between border-t border-white/15 pt-4"><span className="text-[#b4c1dc]">Total you will pay</span><b>{currency(amount+interest)}</b></div></div></div><div className="mt-8"><Link href="/eligibility" className="btn !w-full bg-[#cadef8] text-[#10244d]" data-testid="calculator-eligibility">Check if you may be eligible <ArrowRight size={16}/></Link><p className="mt-4 text-center text-[.7rem] leading-5 text-[#acbad6]">This is only an estimate. It is not a loan offer or approval.</p></div></aside>
  </div>
 </Shell>;
}
function Slider({label,value,min,max,step,display,onChange,testid}:{label:string;value:number;min:number;max:number;step:number;display:string;onChange:(n:number)=>void;testid:string}){
 return <div><div className="mb-3 flex items-center justify-between"><label className="text-sm font-bold text-[#2f436c]">{label}</label><output className="rounded-lg bg-[#eaeef8] px-3 py-1.5 text-sm font-bold text-[#172c56]" data-testid={`${testid}-value`}>{display}</output></div><input className="w-full accent-[#213f7a]" type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} style={{['--fill' as string]:`${((value-min)/(max-min))*100}%`}} data-testid={testid}/><div className="mt-1 flex justify-between text-[.68rem] text-[#8b988f]"><span>{label.includes('amount')?'₹50,000':min}</span><span>{label.includes('amount')?'₹50 lakh':max}</span></div></div>;
}

function About(){
 const site=useSiteConfig();
 return <Shell><PageIntro eyebrow="About Chakrapay" title={<>Loans explained<br/>in simple words.</>} desc="We believe understanding a loan is as important as taking one. So we explain everything clearly, without difficult bank language."/>
 <section className="page-wrap grid gap-12 py-16 md:grid-cols-[1.05fr_.95fr] md:py-20"><div><p className="eyebrow">Our thinking</p><h2 className="serif mt-3 text-4xl leading-tight text-[#10244d] md:text-5xl">Your loan, explained clearly.<br/><em className="font-normal text-[#3097d7]">In words everyone understands.</em></h2><p className="mt-6 leading-7 text-[#4f648d]">Chakrapay is a loan service provider (LSP) built to help people in India compare loan options, understand the likely cost and follow their application, without confusing jargon.</p><p className="mt-4 leading-7 text-[#4f648d]">We do not lend money ourselves. A partner NBFC checks every application and takes all final decisions on sanction and disbursal. We want you to know this from the very first step.</p><Link href="/loans" className="btn btn-primary mt-7">See loan options <ArrowRight size={16}/></Link></div><div className="rounded-[26px] bg-[#e4eaf6] p-8 md:p-10"><p className="eyebrow">What we believe</p><div className="mt-7 space-y-6">{[['Clarity is a kindness','A simple, honest answer is better than a big promise.'],['Your pace matters','Look, calculate, or take a break. The next step is always your choice.'],['Trust comes from small things','We mark indicative rates clearly, tell you who the lender is, and never ask for an advance fee.']].map(([h,p],i)=><div className="flex gap-4" key={h}><span className="serif text-2xl text-[#3ba0de]">0{i+1}</span><div><h3 className="font-bold text-[#1b2f58]">{h}</h3><p className="mt-1 text-sm leading-6 text-[#546993]">{p}</p></div></div>)}</div></div></section>
 <section className="page-wrap pb-6"><div className="grid gap-4 md:grid-cols-[1.4fr_1fr]"><figure className="overflow-hidden rounded-3xl"><img src="/images/about-family.jpg" alt="An Indian family of four sitting together outdoors" width="900" height="600" loading="lazy" className="h-64 w-full object-cover md:h-80"/></figure><figure className="overflow-hidden rounded-3xl"><img src="/images/about-shopkeeper.jpg" alt="A smiling Indian shopkeeper standing in his clothes shop" width="800" height="533" loading="lazy" className="h-64 w-full object-cover md:h-80"/></figure></div></section>
 <section className="bg-[#10244d] py-14 text-[#ebf1f8]"><div className="page-wrap grid gap-8 md:grid-cols-3">{[['We are','A loan service provider (LSP).'],['We are not','A bank or NBFC lender.'],['The lender decides','The partner NBFC takes the final decision on sanction and disbursal.']].map(([h,p])=><div key={h} className="border-l border-[#6ebae9] pl-5"><p className="eyebrow !text-[#78b4da]">{h}</p><p className="mt-3 text-lg">{p}</p></div>)}</div></section><section className="page-wrap py-16"><p className="eyebrow">Company information</p><h2 className="serif mt-2 text-4xl text-[#10244d]">Facts you can check.</h2><p className="mt-4 max-w-2xl leading-7 text-[#4f648d]">Our company, the lender we work with and the person to contact if you have a complaint.</p><div className="mt-7 grid gap-4 md:grid-cols-3">{[['Company',site.company],['Partner NBFC',site.nbfc.name],['Grievance officer',`${site.grievance.name} · ${site.grievance.email}`]].map(([a,b])=><div key={a} className="card p-5"><p className="eyebrow">{a}</p><p className="mt-2 font-semibold text-[#253c69]">{b}</p></div>)}</div></section></Shell>;
}

function Legal(){
 const site=useSiteConfig();
 const nav=[['lsp','Our role'],['rates','Rates & estimates'],['fees','Fees'],['privacy','Privacy policy'],['terms','Terms of use'],['entities','Company & grievance details']];
 return <Shell><PageIntro eyebrow="The important details" title="Our terms, in simple words." desc="Plain-language explanations of who we are, how we use your information and what to expect. Please also read the lender's own documents before you take any loan."/>
 <div className="page-wrap grid gap-8 py-12 md:grid-cols-[230px_1fr]"><nav className="h-fit rounded-2xl bg-[#e4eaf6] p-5"><p className="eyebrow">On this page</p><div className="mt-4 grid gap-3 text-sm font-semibold text-[#334a77]">{nav.map(([id,t])=><a key={id} href={`#${id}`}>{t}</a>)}</div></nav>
 <article className="prose max-w-none prose-headings:font-semibold prose-headings:text-[#10244d] prose-p:text-[#4a5f8a] prose-li:text-[#4a5f8a]">
  <section id="lsp"><p className="eyebrow">01 · Our role</p><h2 className="serif">A service provider, not a lender.</h2><p>{site.lspStatement} We do not lend money, promise loan approval or make credit decisions. A partner NBFC checks every application and takes the final decision on sanction, loan terms and disbursal. Please do not treat an estimate or eligibility result as an approval.</p></section>
  <section id="rates"><p className="eyebrow">02 · Indicative information</p><h2 className="serif">Estimates, not promises.</h2><p>{site.ratesDisclaimer} Rates can change and may not include charges, taxes or other costs. The EMI calculator and the eligibility check give an idea only. Always read the lender's final documents before you accept a loan.</p></section>
  <section id="fees"><p className="eyebrow">03 · Fees</p><h2 className="serif">No advance or processing fee.</h2><p><strong>{site.noFeeLine}</strong> Do not pay anyone who promises loan approval in return for an advance fee. If the lender has any charges, the partner NBFC must tell you about them in its official documents.</p></section>
  <section id="privacy"><p className="eyebrow">04 · Privacy policy</p><h2 className="serif">How we use your information.</h2>
   <p><strong>What we collect.</strong> Only what is needed: your name, mobile number, email, city, the loan type and amount you want, your income and existing EMIs. If you create an account, we also keep your password in encrypted form. If you upload documents, we store them privately.</p>
   <p><strong>Why we collect it.</strong> To process your loan enquiry, to share it with our partner NBFC for assessment, to let our team call you about the next steps, and to send you updates about your application by email.</p>
   <p><strong>Who can see it.</strong> You, our team members who handle your application, and the partner NBFC. Your documents are never public. They open only after login, only for people who are allowed to see them, and every access is recorded.</p>
   <p><strong>Your consent.</strong> When you apply, we record the time and the version of the consent text you agreed to.</p>
   <p><strong>Your choices.</strong> You can ask us to correct, delete or anonymise your data by writing to our grievance officer below.</p>
   <p className="text-xs">This policy is a draft and will be reviewed with our legal adviser. Its final wording may change.</p></section>
  <section id="terms"><p className="eyebrow">05 · Terms of use</p><h2 className="serif">Using this website.</h2><p>Please give correct information. Do not misuse the website or try to access other people's data. Applying is free and does not guarantee a loan. We may update these terms from time to time, and the latest version is always on this page.</p></section>
  <section id="entities"><p className="eyebrow">06 · Company and grievance details</p><h2 className="serif">Who to contact.</h2>
   <ul><li>Company: {site.company}</li><li>Address: {site.address}</li><li>Registration (CIN): {site.cin}</li><li>Partner NBFC (lender): {site.nbfc.url?<a href={site.nbfc.url} target="_blank" rel="noopener noreferrer">{site.nbfc.name}</a>:site.nbfc.name}</li><li>Grievance officer: {site.grievance.name} · {site.grievance.email}{site.grievance.phone?` · ${site.grievance.phone}`:''}</li><li>Support email: {site.email}</li></ul></section>
 </article></div></Shell>;
}

function NotFoundPage(){return <Shell><div className="page-wrap py-24 text-center"><p className="eyebrow">Page not found</p><h1 className="serif mt-3 text-5xl text-[#10244d]">Oops, wrong turn.</h1><p className="mt-4 text-[#586d98]">We could not find the page you are looking for.</p><Link href="/" className="btn btn-primary mt-7">Back home <ArrowRight size={16}/></Link></div></Shell>}

function App(){
 const [path] = useLocation();
 if(path.startsWith('/admin')) return <AdminApp/>;
 return <Switch>
  <Route path="/" component={Home}/>
  <Route path="/about" component={About}/>
  <Route path="/loans" component={Loans}/>
  <Route path="/calculator" component={Calculator}/>
  <Route path="/eligibility" component={Eligibility}/>
  <Route path="/apply" component={Apply}/>
  <Route path="/contact" component={Contact}/>
  <Route path="/legal" component={Legal}/>
  <Route path="/login">{()=> <AuthPage kind="login"/>}</Route>
  <Route path="/signup">{()=> <AuthPage kind="signup"/>}</Route>
  <Route path="/forgot-password">{()=> <AuthPage kind="forgot"/>}</Route>
  <Route path="/verify-email">{()=> <AuthPage kind="verify"/>}</Route>
  <Route path="/reset-password">{()=> <AuthPage kind="reset"/>}</Route>
  <Route path="/applications">{()=> <Applications/>}</Route>
  <Route path="/account/applications" component={Applications}/>
  <Route path="/account/applications/:id">{params=><ApplicationDetail id={params.id}/>}</Route>
  <Route path="/account/profile" component={Profile}/>
  <Route component={NotFoundPage}/>
 </Switch>;
}
export default App;